name: Intro_SnowML
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - ipykernel
  - pre-commit
  - seaborn
  - snowflake-snowpark-python[pandas]
  - scikit-learn
  - xgboost
  - pip:
    - snowflake-ml-python # temporary till it's in the Snowflake conda channel
