name: Intro_SnowML
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - ipykernel
  - nbconvert
  - nbformat
  - python-dotenv
  - seaborn
  - scikit-learn
  - xgboost
  - snowflake-snowpark-python[pandas]
  - scikit-learn
  - xgboost
  - pip:
      - snowflake-ml-python
