name: Test Dependencies

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.ipynb'
      - 'environment.yml'
      - 'run.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Download and install Micromamba
        run: |
          "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
          micromamba shell init --shell bash --root-prefix=~/micromamba
          export PATH="$HOME/micromamba/bin:$PATH"

      - name: Create Micromamba environment and run Jupyter notebooks
        run: |
          micromamba create --file environment.yml --yes
          echo "source ~/micromamba/etc/profile.d/mamba.sh" >> $GITHUB_ENV
          micromamba activate Intro_SnowML
          micromamba list  # Optional: to verify that the environment has the correct packages
          python run.py  # This assumes your environment activation persists to this command
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
